# Generated by Django 4.2.1 on 2023-05-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0002_custom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custom",
            name="activity",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="custom",
            name="date",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="custom",
            name="destnation",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="custom",
            name="duration",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="custom",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
