# Generated by Django 4.2.1 on 2023-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0003_alter_custom_activity_alter_custom_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=100, null=True)),
                ("price", models.CharField(max_length=100, null=True)),
                ("img", models.ImageField(upload_to="pics")),
            ],
        ),
    ]
