# Generated by Django 4.2.1 on 2023-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0005_alter_blogs_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="iframe",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
