# Generated by Django 4.1.7 on 2023-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0006_blogs_iframe"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="tag",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
