# Generated by Django 4.1.7 on 2023-06-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0009_order_rename_destination_product_orderitem_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="product",
            new_name="Destination",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
