# Generated by Django 4.1.7 on 2023-06-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0012_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rating",
            name="unlikes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
