# Generated by Django 4.2.1 on 2023-06-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0015_order_product_orderitem_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
    ]
