# Generated by Django 4.2.1 on 2023-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0016_remove_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
