# Generated by Django 4.2.1 on 2023-06-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0017_order_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
