# Generated by Django 4.2.1 on 2023-06-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0018_remove_orderitem_order_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("quantity", models.CharField(max_length=200, null=True)),
                ("date_ordered", models.DateTimeField(auto_now_add=True, null=True)),
                ("complete", models.BooleanField(blank=True, default=False, null=True)),
                ("transaction_id", models.CharField(max_length=200, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stroll1.customer",
                    ),
                ),
                ("product", models.ManyToManyField(to="stroll1.product")),
            ],
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stroll1.order",
            ),
        ),
    ]
