# Generated by Django 4.2.1 on 2023-06-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0024_remove_orderitem_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order1",
            new_name="Order",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stroll1.order",
            ),
        ),
    ]
