# Generated by Django 4.2.1 on 2023-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0028_remove_order_name_remove_order_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash on Delivery", "Cash on Delivery"),
                    ("Khalti", "Khalti"),
                    ("Esewa", "Esewa"),
                ],
                default="Cash on delivery",
                max_length=20,
            ),
        ),
    ]
