# Generated by Django 4.2.1 on 2023-06-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0029_order_payment_completed_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_by", models.CharField(max_length=200)),
                ("shipping_address", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subtotal", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Order Received", "Order Received"),
                            ("Order Processing", "Order Processing"),
                            ("On the way", "On the way"),
                            ("Order Completed", "Order Completed"),
                            ("Order Canceled", "Order Canceled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash on Delivery", "Cash on Delivery"),
                            ("Khalti", "Khalti"),
                            ("Esewa", "Esewa"),
                        ],
                        default="Cash On Delivery",
                        max_length=20,
                    ),
                ),
                (
                    "payment_completed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
    ]
