# Generated by Django 4.2.1 on 2023-06-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0030_destination_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination_order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="order_status",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="ordered_by",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="destination_order",
            name="total",
        ),
    ]
