# Generated by Django 4.2.1 on 2023-06-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0031_remove_destination_order_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination_order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="destination_order",
            name="mobile",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="destination_order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Order Received", "Order Received"),
                    ("Order Processing", "Order Processing"),
                    ("On the way", "On the way"),
                    ("Order Completed", "Order Completed"),
                    ("Order Canceled", "Order Canceled"),
                ],
                default="Order Received",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="destination_order",
            name="ordered_by",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
