# Generated by Django 4.2.1 on 2023-06-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0032_destination_order_email_destination_order_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination_order",
            name="destination",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
