# Generated by Django 4.2.1 on 2023-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0033_destination_order_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination_order",
            name="date_ordered",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
