# Generated by Django 4.2.2 on 2023-06-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stroll1", "0035_destination_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="img",
            field=models.ImageField(null=True, upload_to="pics"),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stroll1.customer",
                    ),
                ),
            ],
        ),
    ]
